In [1]:
# Import pandas
import pandas as pd

In [2]:
# Create a DataFrame with balance.txt
df = pd.read_csv('balance.txt', sep = ' ')

Write the code needed to produce a report that provides the following information:
* Compare the average income based on ethnicity.
* On average, do married or single people have a higher balance?
* What is the highest income in our dataset?
* What is the lowest income in our dataset?
* How many cards do we have recorded in our dataset? (Hint: use `sum()`)
* How many females do we have information for vs how many males? (Hint: use `count()` for a list of all methods for computation of descriptive stats, explore the [pandas documentation](https://pandas.pydata.org/pandas-docs/stable/reference/frame.html#computations-descriptive-stats)).

In [3]:
# Compare the average income based on ethnicity.
average_income_by_ethnicity = df.groupby('Ethnicity')['Income'].mean()
print(average_income_by_ethnicity)

Ethnicity
African American    47.682101
Asian               44.187833
Caucasian           44.521945
Name: Income, dtype: float64

In [10]:
# On average, do married or single people have a higher balance?
average_balance_by_marital_status = df.groupby('Married')['Balance'].mean()
print(average_balance_by_marital_status)

Married
No     13.493509
Yes    13.388473
Name: Balance, dtype: float64

In [13]:
# What is the highest income in our dataset?
highest_income = df['Income'].max()
print(highest_income)

186.634

In [6]:
# What is the lowest income in our dataset?
lowest_income = df['Income'].min()
print(lowest_income)

10.354

In [7]:
# How many cards do we have recorded in our dataset?
cards_sum = df['Cards'].sum()
print(cards_sum)

1183

In [8]:
# How many females do we have information for vs how many males?
gender_count = df['Gender'].value_counts()
print(gender_count)

Gender
Female    207
Male      193
Name: count, dtype: int64